### ISSUE TITLE
Usage with iobroker not possible atm -> "number"-type not supported

### ISSUE THREAD

**Issue by 4eversr** [wildekek/rd6006-controller#4]
Hi, i have sucessfully running this wildekek RD6006-controller in an test environment with HA. - But unfortunately (for me) i don't use HA in my productive environment, i use iobroker. - In iobroker there is an ESPHOME-Adapter, too, but this adapter does not support the type "number" you used in your RD6006-controller script.

Would it be possible to replace the "number" part in your script to something the iobroker ESPHOME adapter will support, too ? My goal is to be able to control just the current of the RD6006, because the Riden RD6006 would be an iobroker-controlled adaptive solar charger for my lifepo4 battery (in my environment). - If it is possible to replace the "number"-type with something else perhaps you can give a code example i can adapt to !?

Here is the docu from the iobroker ESPHOME-adapter which unfortunately don't support the "number" type:
https://drozmotix.github.io/languages/en/Adapter/ESPHome/02.supportedTypes.html

( BTW: Will this script possibly work with other Riden models too, like the 18A version RD6018 ? )

Greetings from Germany
Thomas

**Comment by wildekek** [comment]
Hi Thomas,
I'm not familiar with iobroker, but looking at the docs it seems they do not support writing any state to esphome except for the switch type. I think the only option would be to try and get number support in iobroker. I see you already created an issue [here](https://github.com/DrozmotiX/ioBroker.esphome/issues/132).
What you could do as a (nasty) workaround though, is create a bunch of switches in esphome and set the current by manipulating switches in iobroker. A switch is a bit, so you could create 8 switches and have 1 integer of current precision. Not pretty, but it could work.

**Comment by wildekek** [comment]
As for you question about RD6018, I created a new issue [here](https://github.com/wildekek/rd6006-controller/issues/5), hope that answers your question.
